# Generated by Django 6.0.3 on 2026-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_seed_default_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
