# Generated by Django 6.0.3 on 2026-08-28 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEssai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('entreprise', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('converti', 'Converti'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('note_interne', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('organisation_creee', models.ForeignKey(blank=True, help_text='Renseigné une fois la demande convertie en organisation cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.organisation')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
