# Generated by Django 6.0.3 on 2026-08-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_demandeessai'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.TextField(blank=True, default='', help_text="Logo de l'organisation, en data URI base64 — affiché sur ses rapports et certificats (ExtincPro fournit le logiciel, chaque organisation garde sa marque)."),
        ),
    ]
