# Generated by Django 6.0.3 on 2026-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_seed_rapport_eclairage_urgence_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', help_text="Langue de l'interface et des documents générés (rapports, certificats) pour cette organisation.", max_length=2),
        ),
    ]
