# Generated by Django 6.0.3 on 2026-09-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_seed_rapport_cuisine_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='date_fin_essai',
            field=models.DateField(blank=True, help_text="Date de fin de l'essai gratuit — vide une fois l'organisation confirmée comme cliente payante. Un courriel d'avis est envoyé automatiquement 7 jours avant.", null=True),
        ),
    ]
