# Generated by Django 6.0.3 on 2026-10-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_seed_rapport_gicleur_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ms_client_id',
            field=models.PositiveIntegerField(blank=True, help_text="Client correspondant dans MS Solution Informatique (facturation). Une fois renseigné, les modules, la fin d'essai et l'accès sont pilotés par MS Solution.", null=True, unique=True),
        ),
        migrations.CreateModel(
            name='JournalIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_nom', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=50)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_integration', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
