# Generated by Django 6.0.3 on 2026-10-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_integration_ms_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeessai',
            name='nb_techniciens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeessai',
            name='neq',
            field=models.CharField(blank=True, help_text="Numéro d'entreprise du Québec.", max_length=20, verbose_name='NEQ'),
        ),
        migrations.AddField(
            model_name='demandeessai',
            name='site_web',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
