# Generated by Django 6.0.3 on 2026-07-16 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_civique', models.CharField(max_length=10)),
                ('rue', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('fabricant_reseau', models.CharField(blank=True, max_length=100)),
                ('modele_systeme', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(blank=True, help_text='Secteur / direction responsable', max_length=100)),
                ('type_application', models.CharField(choices=[('residentiel', 'Résidentiel'), ('commercial', 'Commercial'), ('industriel', 'Industriel')], default='residentiel', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(blank=True, help_text="Le citoyen qui consultera ce rapport/certificat, s'il y en a un.", limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batiments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batiments', to='inspections.client')),
            ],
            options={
                'ordering': ['rue', 'numero_civique'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_inspection', models.DateField(blank=True, help_text="Jour prévu de la visite — sert au filtre 'aujourd'hui' du technicien.", null=True)),
                ('date_prise_effet', models.DateField(blank=True, null=True)),
                ('date_derniere_sauvegarde', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='inspections.batiment')),
                ('citoyen', models.ForeignKey(blank=True, help_text='Le citoyen qui pourra consulter ce rapport et son certificat.', limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_citoyen', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='rapports_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inspections.rapport')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='FicheE2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('description_panneau', models.CharField(blank=True, max_length=200)),
                ('tension_sous_alimentation', models.CharField(blank=True, max_length=20)),
                ('tension_pleine_charge', models.CharField(blank=True, max_length=20)),
                ('courant_charge', models.CharField(blank=True, max_length=20)),
                ('code_dateur_batterie', models.CharField(blank=True, max_length=10)),
                ('signal_alarme_ok', models.BooleanField(blank=True, null=True)),
                ('rearmement_ok', models.BooleanField(blank=True, null=True)),
                ('commutation_alimentation_ok', models.BooleanField(blank=True, null=True)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_e2', to='inspections.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='FicheE1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonctionnement_une_etape', models.BooleanField(blank=True, null=True)),
                ('fonctionnement_deux_etapes', models.BooleanField(blank=True, null=True)),
                ('inspection_essai_conforme', models.BooleanField(blank=True, null=True)),
                ('documentation_sur_place', models.BooleanField(blank=True, null=True)),
                ('reseau_fonctionnel', models.BooleanField(blank=True, null=True)),
                ('lacunes_constatees', models.BooleanField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('copie_remise_responsable', models.BooleanField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('signataire', models.ForeignKey(blank=True, help_text='Le technicien qui a fermé le rapport — certifie que les renseignements sont exacts et complets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_e1_signees', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_e1', to='inspections.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=200)),
                ('type_dispositif', models.CharField(choices=[('S', 'Détecteur de fumée'), ('RHT', 'Détecteur de chaleur réarmable'), ('HT', 'Détecteur de chaleur non réarmable'), ('M', 'Avertisseur manuel'), ('B', 'Cloche'), ('AFE', 'Avertisseur de fumée électrique'), ('UN72-6', "Éclairage d'urgence"), ('PAI', "Panneau d'alarme incendie")], max_length=10)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('installation_correcte', models.BooleanField(default=True)),
                ('necessite_entretien', models.BooleanField(default=False)),
                ('alarme_confirmee', models.BooleanField(default=True)),
                ('annonce_confirmee', models.BooleanField(default=True)),
                ('zone_circuit', models.CharField(blank=True, max_length=20)),
                ('remarque', models.CharField(blank=True, max_length=300)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositifs', to='inspections.rapport')),
            ],
            options={
                'ordering': ['localisation'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='certificats/')),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_emis', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='inspections.rapport')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
