# Generated by Django 6.0.3 on 2026-08-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extincteuritem',
            name='etat',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('C', 'Conforme'), ('I', 'Inspecté'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
    ]
