# Generated by Django 6.0.3 on 2026-07-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositif',
            options={'ordering': ['section__ordre', 'localisation']},
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='localisation',
            field=models.CharField(help_text='Emplacement précis dans la section — ex. « App. 312 »', max_length=200),
        ),
        migrations.CreateModel(
            name='SectionDispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inspections.rapport')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dispositif',
            name='section',
            field=models.ForeignKey(blank=True, help_text="La zone/l'étage auquel ce dispositif appartient.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositifs', to='inspections.sectiondispositif'),
        ),
    ]
