# Generated by Django 6.0.3 on 2026-07-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_dispositif_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSommaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_generales', models.TextField(blank=True)),
                ('resume_citoyen', models.TextField(blank=True, help_text='Résumé en langage simple, sans jargon technique, destiné au citoyen.')),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_sommaire', to='inspections.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='EtageResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. « Sous-sol », « 3e étage »', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('etat', models.CharField(choices=[('bon', 'Bon'), ('acceptable', 'Acceptable'), ('a_reviser', 'À réviser')], default='bon', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etages', to='inspections.resumesommaire')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
