# Generated by Django 6.0.3 on 2026-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_dispositif_annonce_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositif',
            name='type_dispositif',
            field=models.CharField(choices=[('S', 'Détecteur de fumée'), ('RHT', 'Détecteur de chaleur réarmable'), ('HT', 'Détecteur de chaleur non réarmable'), ('M', 'Avertisseur manuel'), ('B', 'Cloche'), ('AFE', 'Avertisseur de fumée électrique'), ('UN72-6', "Éclairage d'urgence"), ('PAI', "Panneau d'alarme incendie"), ('K', 'Klaxon'), ('FDL', 'Résistance de fin de ligne'), ('PZ', 'Piézo'), ('ISO', 'Module isolateur'), ('ANN', "Panneau annonciateur d'alarme"), ('DFG', 'Détecteur de fumée gaine ventilation'), ('TEL', "Téléphone d'urgence (pompier)"), ('IDG', 'Gicleur débit'), ('IVG', 'Interrupteur vanne gicleur'), ('IHP', 'Interrupteur haute pression'), ('IBH', 'Interrupteur de basse pression'), ('K/S', 'Klaxon strobe'), ('MA', 'Module adressable')], max_length=10),
        ),
    ]
