# Generated by Django 6.0.3 on 2026-08-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_alter_dispositif_type_dispositif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositif',
            options={'ordering': ['section__ordre', 'id']},
        ),
    ]
