# Generated by Django 6.0.3 on 2026-08-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_alter_dispositif_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheLegende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositifs', models.JSONField(blank=True, default=dict, help_text="JSON par code d'abréviation : { 'PAI': {'type': '', 'modele': ''}, ... }")),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_legende', to='inspections.rapport')),
            ],
        ),
    ]
