# Generated by Django 6.0.3 on 2026-08-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_fichelegende'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositif',
            name='alarme_confirmee',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='installation_correcte',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='necessite_entretien',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
