# Generated by Django 6.0.3 on 2026-08-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_alter_dispositif_alarme_confirmee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportExtincteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_job', models.CharField(blank=True, help_text='Champ « JOB » du formulaire papier.', max_length=50)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_inspection', models.DateField(blank=True, null=True)),
                ('date_derniere_sauvegarde', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_extincteurs', to='inspections.batiment')),
                ('citoyen', models.ForeignKey(blank=True, help_text='Le citoyen qui pourra consulter ce rapport et son certificat.', limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_extincteurs_citoyen', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_extincteurs_crees', to=settings.AUTH_USER_MODEL)),
                ('rapport_alarme', models.ForeignKey(blank=True, help_text='Le rapport du réseau avertisseur créé en même temps, pour la même adresse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_extincteurs', to='inspections.rapport')),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='rapports_extincteurs_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRapportExtincteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inspections.rapportextincteur')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='ExtincteurItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage', models.CharField(blank=True, max_length=100)),
                ('emplacement', models.CharField(blank=True, max_length=200)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
                ('format', models.CharField(blank=True, choices=[('2.5lb', '2.5 lb'), ('5lb', '5 lb'), ('10lb', '10 lb'), ('20lb', '20 lb'), ('2.5kg', '2.5 kg'), ('5kg', '5 kg'), ('10kg', '10 kg'), ('autre', 'Autre')], max_length=10)),
                ('type_extincteur', models.CharField(blank=True, choices=[('ABC', 'Poudre ABC'), ('BC', 'Poudre BC'), ('CO2', 'CO2'), ('EAU', 'Eau'), ('AFFF', 'Mousse (AFFF)'), ('K', 'Produits chimiques humides (K)'), ('autre', 'Autre')], max_length=10)),
                ('marque', models.CharField(blank=True, choices=[('amerex', 'Amerex'), ('kidde', 'Kidde'), ('buckeye', 'Buckeye'), ('ansul', 'Ansul'), ('general', 'General'), ('flag', 'Flag'), ('autre', 'Autre')], max_length=10)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('prochaine_maintenance', models.DateField(blank=True, null=True)),
                ('prochain_test_hydrostatique', models.DateField(blank=True, null=True)),
                ('remarque', models.CharField(blank=True, max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extincteurs', to='inspections.rapportextincteur')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CertificatExtincteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('certificat_envoye', models.BooleanField(default=False, help_text='True quand le superviseur envoie explicitement le certificat au citoyen.')),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_extincteurs_emis', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='inspections.rapportextincteur')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
