# Generated by Django 6.0.3 on 2026-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_rapportextincteur_historiquerapportextincteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extincteuritem',
            name='etat',
            field=models.CharField(choices=[('D', 'Défectueux'), ('I', 'Inspecté'), ('NI', 'Non inspecté')], default='NI', max_length=2),
        ),
    ]
