# Generated by Django 6.0.3 on 2026-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_extincteuritem_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositif',
            name='alarme_confirmee',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='annonce_statut',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('I', 'Inspecté'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='installation_correcte',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='necessite_entretien',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
