# Generated by Django 6.0.3 on 2026-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_alter_dispositif_alarme_confirmee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extincteuritem',
            name='etat',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('I', 'Inspecté'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
    ]
