# Generated by Django 6.0.3 on 2026-08-20 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_alter_dispositif_type_dispositif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_inspection', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='ouvert', max_length=10)),
                ('date_assignation', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_terminaison', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pubms_tache_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pubms_sync_status', models.CharField(choices=[('non_synchronise', 'Non synchronisé'), ('synchronise', 'Synchronisé'), ('echec', 'Échec de synchronisation')], default='non_synchronise', max_length=20)),
                ('pubms_sync_error', models.TextField(blank=True)),
                ('pubms_sync_tentatives', models.PositiveIntegerField(default=0)),
                ('date_dernier_sync', models.DateTimeField(blank=True, null=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_service', to='inspections.batiment')),
                ('cree_par', models.ForeignKey(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.PROTECT, related_name='appels_service_crees', to=settings.AUTH_USER_MODEL)),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='appels_service_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAppelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inspections.appelservice')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
