# Generated by Django 6.0.3 on 2026-08-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_appelservice_historiqueappelservice'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organisations.organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('organisation', 'nom')},
        ),
    ]
