# Generated by Django 6.0.3 on 2026-08-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_client_organisation_alter_client_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extincteuritem',
            name='etat',
            field=models.CharField(blank=True, choices=[('D', 'Défectueux'), ('C', 'Conforme'), ('NI', 'Non inspecté')], default=None, max_length=2, null=True),
        ),
    ]
