# Generated by Django 6.0.3 on 2026-08-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_extincteuritem_dates_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extincteuritem',
            name='format',
            field=models.CharField(blank=True, choices=[('2.5lb', '2.5 lb'), ('5lb', '5 lb'), ('10lb', '10 lb'), ('13.25lb', '13.25 lb'), ('20lb', '20 lb'), ('2.5kg', '2.5 kg'), ('5kg', '5 kg'), ('10kg', '10 kg'), ('6L', '6 L'), ('autre', 'Autre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='extincteuritem',
            name='marque',
            field=models.CharField(blank=True, choices=[('amerex', 'Amerex'), ('kidde', 'Kidde'), ('buckeye', 'Buckeye'), ('ansul', 'Ansul'), ('general', 'General'), ('flag', 'Flag'), ('strikefirst', 'Strike First'), ('autre', 'Autre')], max_length=15),
        ),
        migrations.AlterField(
            model_name='extincteuritem',
            name='type_extincteur',
            field=models.CharField(blank=True, choices=[('ABC', 'Poudre ABC'), ('BC', 'Poudre BC'), ('CO2', 'CO2'), ('EAU', 'Eau'), ('AFFF', 'Mousse (AFFF)'), ('K', 'Produits chimiques humides (K)'), ('halotron', 'Halotron'), ('fe36', 'FE36'), ('autre', 'Autre')], max_length=10),
        ),
    ]
