# Generated by Django 6.0.3 on 2026-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0021_alter_extincteuritem_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mode_livraison',
            field=models.CharField(choices=[('plateforme', 'Espace client (invitation)'), ('direct', 'Envoi direct par courriel (PDF joint)')], default='plateforme', help_text="« Direct » : pas de compte à créer — le rapport et le certificat PDF sont envoyés directement à contact_email dès qu'ils sont prêts. Recommandé pour les clients avec peu de bâtiments (moins de 5).", max_length=20),
        ),
    ]
