# Generated by Django 6.0.3 on 2026-09-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_client_mode_livraison'),
        ('inspections', '0022_rapporteclairageurgence_and_more'),
    ]

    operations = [
    ]
