# Generated by Django 6.0.3 on 2026-09-06 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_merge_20260904_1328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_job', models.CharField(blank=True, help_text='Champ « JOB » du formulaire papier.', max_length=50)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('courtier', models.CharField(blank=True, max_length=150)),
                ('fabricant', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('type_agent', models.CharField(blank=True, choices=[('liquide', 'Liquide (wet chemical)'), ('poudre', 'Poudre chimique'), ('co2', 'CO2'), ('autre', 'Autre')], max_length=10)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('alimentation', models.CharField(blank=True, help_text='Ex. « Gaz », « Électrique »', max_length=150)),
                ('dispositif_coupure', models.CharField(blank=True, choices=[('valve_gaz', 'Valve(s) à gaz'), ('contacteur', 'Contacteur')], max_length=15)),
                ('nombre_buses', models.PositiveIntegerField(blank=True, help_text='Nombre total de buses du système', null=True)),
                ('liens_fusibles_360f', models.PositiveIntegerField(blank=True, null=True, verbose_name='Liens fusibles 360°F')),
                ('liens_fusibles_450f', models.PositiveIntegerField(blank=True, null=True, verbose_name='Liens fusibles 450°F')),
                ('liens_fusibles_500f', models.PositiveIntegerField(blank=True, null=True, verbose_name='Liens fusibles 500°F')),
                ('buses_liens_fusibles', models.CharField(blank=True, help_text='Ex. « 6 buses · 360° (remplacés) »', max_length=200)),
                ('date_dernier_essai_hydrostatique', models.DateField(blank=True, null=True)),
                ('date_derniere_recharge', models.DateField(blank=True, null=True)),
                ('prochaine_inspection', models.DateField(blank=True, null=True)),
                ('raccordement', models.CharField(blank=True, help_text="Ex. « Relié au panneau d'alarme »", max_length=150)),
                ('appareils_proteges', models.BooleanField(blank=True, default=None, null=True)),
                ('liens_fusibles_remplaces', models.BooleanField(blank=True, default=None, null=True)),
                ('installation_conforme_fabricant', models.BooleanField(blank=True, default=None, null=True)),
                ('cable_tension_verifie', models.BooleanField(blank=True, default=None, null=True)),
                ('pression_manometre_verifiee', models.BooleanField(blank=True, default=None, null=True)),
                ('conduits_decharge_verifies', models.BooleanField(blank=True, default=None, null=True)),
                ('cylindres_supports_inspectes', models.BooleanField(blank=True, default=None, null=True)),
                ('extincteur_portatif_type_k', models.BooleanField(blank=True, default=None, null=True)),
                ('station_manuelle_degagee', models.BooleanField(blank=True, default=None, null=True)),
                ('etiquettes_verification_apposees', models.BooleanField(blank=True, default=None, null=True)),
                ('buses_protecteurs_nettoyes', models.BooleanField(blank=True, default=None, null=True)),
                ('systeme_condition_normale', models.BooleanField(blank=True, default=None, null=True)),
                ('liens_fusibles_nettoyes', models.BooleanField(blank=True, default=None, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('date_inspection', models.DateField(blank=True, null=True)),
                ('date_derniere_sauvegarde', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_cuisine', to='inspections.batiment')),
                ('cree_par', models.ForeignKey(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_cuisine_crees', to=settings.AUTH_USER_MODEL)),
                ('rapport_extincteur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_cuisine_lie', to='inspections.rapportextincteur')),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='rapports_cuisine_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HotteCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('nombre_buses', models.PositiveIntegerField(blank=True, null=True)),
                ('appareils', models.JSONField(blank=True, default=list)),
                ('dividers', models.JSONField(blank=True, default=list)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hottes', to='inspections.rapportcuisine')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRapportCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inspections.rapportcuisine')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
