# Generated by Django 6.0.3 on 2026-09-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0024_rapportcuisine_hottecuisine_historiquerapportcuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificat',
            name='envoye_a',
            field=models.CharField(blank=True, help_text="Courriel ou nom d'utilisateur destinataire, au moment de l'envoi.", max_length=255),
        ),
        migrations.AddField(
            model_name='certificat',
            name='mode_envoi',
            field=models.CharField(blank=True, choices=[('direct', 'Courriel direct'), ('citoyen', 'Espace citoyen')], max_length=10),
        ),
        migrations.AddField(
            model_name='certificatextincteur',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatextincteur',
            name='envoye_a',
            field=models.CharField(blank=True, help_text="Courriel ou nom d'utilisateur destinataire, au moment de l'envoi.", max_length=255),
        ),
        migrations.AddField(
            model_name='certificatextincteur',
            name='mode_envoi',
            field=models.CharField(blank=True, choices=[('direct', 'Courriel direct'), ('citoyen', 'Espace citoyen')], max_length=10),
        ),
    ]
