# Generated by Django 6.0.3 on 2026-09-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0025_certificat_date_envoi_certificat_envoye_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottecuisine',
            name='buses',
            field=models.JSONField(blank=True, default=list, help_text="Positions horizontales des buses, placées manuellement — [{'x': 120}, ...], comme `appareils`."),
        ),
        migrations.AlterField(
            model_name='hottecuisine',
            name='nombre_buses',
            field=models.PositiveIntegerField(blank=True, help_text="Ancien champ (comptage seulement) — remplacé par `buses` (positions), gardé pour l'historique des hottes créées avant.", null=True),
        ),
    ]
