# Generated by Django 6.0.3 on 2026-09-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0026_hottecuisine_buses_alter_hottecuisine_nombre_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='prochaine_inspection',
            field=models.DateField(blank=True, help_text='Calculée automatiquement à la fermeture (date_inspection + 1 an) — sert aux rappels par courriel.', null=True),
        ),
        migrations.AddField(
            model_name='rapporteclairageurgence',
            name='prochaine_inspection',
            field=models.DateField(blank=True, help_text='Calculée automatiquement à la fermeture (date_inspection + 1 an) — sert aux rappels par courriel.', null=True),
        ),
        migrations.AddField(
            model_name='rapportextincteur',
            name='prochaine_inspection',
            field=models.DateField(blank=True, help_text='Calculée automatiquement à la fermeture (date_inspection + 1 an) — sert aux rappels par courriel.', null=True),
        ),
    ]
