# Generated by Django 6.0.3 on 2026-09-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0027_rapport_prochaine_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportextincteur',
            name='rapport_precedent',
            field=models.OneToOneField(blank=True, help_text="Le rapport dont celui-ci a été généré automatiquement à la fermeture — permet de retrouver le brouillon déjà préparé plutôt que d'en recréer un doublon.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillon_suivant', to='inspections.rapportextincteur'),
        ),
    ]
