# Generated by Django 6.0.3 on 2026-09-11 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0028_rapportextincteur_rapport_precedent'),
        ('organisations', '0009_organisation_date_fin_essai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('date_tournee', models.DateField(help_text='Jour où la tournée doit être effectuée.')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.PROTECT, related_name='tournees_creees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='organisations.organisation')),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='tournees_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_tournee'],
            },
        ),
        migrations.CreateModel(
            name='TourneeBatiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('visite', models.BooleanField(default=False, help_text='Coché par le technicien une fois la visite complétée.')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_tournee', to='inspections.batiment')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='inspections.tournee')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('tournee', 'batiment')},
            },
        ),
        migrations.AddField(
            model_name='tournee',
            name='batiments',
            field=models.ManyToManyField(related_name='tournees', through='inspections.TourneeBatiment', to='inspections.batiment'),
        ),
    ]
