# Generated by Django 6.0.3 on 2026-09-11 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0029_tournee_tourneebatiment_tournee_batiments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourneebatiment',
            name='techniciens',
            field=models.ManyToManyField(blank=True, help_text="Technicien(s) assignés spécifiquement à cette étape. Vide = n'importe quel technicien de la tournée peut la couvrir. Permet de diviser un même secteur entre plusieurs techniciens (chacun sa portion de la route) plutôt que tous sur tous les arrêts.", limit_choices_to={'role': 'technicien'}, related_name='etapes_tournee_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
