# Generated by Django 6.0.3 on 2026-09-26 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0030_tourneebatiment_techniciens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportGicleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_job', models.CharField(blank=True, help_text='Champ « JOB » du formulaire papier.', max_length=50)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_inspection', models.DateField(blank=True, null=True)),
                ('date_derniere_sauvegarde', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prochaine_inspection', models.DateField(blank=True, help_text='Calculée automatiquement à la fermeture (date_inspection + 1 an) — sert aux rappels par courriel.', null=True)),
                ('identification_systeme', models.CharField(blank=True, max_length=150)),
                ('local_gicleur', models.CharField(blank=True, help_text='Local des vannes/gicleurs.', max_length=150)),
                ('type_systeme', models.CharField(blank=True, choices=[('eau', 'Sous eau (wet-pipe)'), ('air', 'Sous air (dry-pipe)'), ('deluge', 'Déluge'), ('preaction', 'Préaction'), ('combine', 'Combiné')], max_length=20)),
                ('frequence_inspection', models.CharField(blank=True, choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle'), ('mensuelle', 'Mensuelle')], max_length=20)),
                ('compagnie_installatrice', models.CharField(blank=True, max_length=150)),
                ('recommandations', models.TextField(blank=True, help_text="Modifications récentes de l'affectation des locaux ou du matériel d'incendie.")),
                ('ajustements_effectues', models.TextField(blank=True, help_text='Ajustements ou corrections effectués lors de la visite.')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_gicleurs', to='inspections.batiment')),
                ('citoyen', models.ForeignKey(blank=True, help_text='Le citoyen qui pourra consulter ce rapport et son certificat.', limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_gicleurs_citoyen', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_gicleurs_crees', to=settings.AUTH_USER_MODEL)),
                ('techniciens', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technicien'}, related_name='rapports_gicleurs_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAnomalieGicleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('emplacement', models.CharField(help_text='Titre de la photo, ex. « Sous-sol — salle mécanique ».', max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('ajoutee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRapportGicleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='GicleurValveEtageSupervise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('texte', models.TextField(blank=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves_etage_supervise', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GicleurSoupapeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('categorie', models.CharField(choices=[('ville', 'Soupapes de commande de la ville'), ('alimentation', "Soupapes de commande d'alimentation"), ('pompe', 'Soupapes de commande de pompe'), ('secteur', 'Soupapes de commande de secteur'), ('principale', 'Soupapes de commande principales')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('type_texte', models.CharField(blank=True, max_length=100)),
                ('ouvertes', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('protegees', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('identifiees', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('condition', models.CharField(blank=True, max_length=150)),
                ('localisation', models.CharField(blank=True, max_length=150)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soupapes_commande', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GicleurReponseNegative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('texte', models.TextField()),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_negatives', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GicleurPointBas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('vidange', models.CharField(blank=True, choices=[('oui', 'Oui'), ('na', 'S/O'), ('non', 'Non')], max_length=3)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_bas', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GicleurInstallationSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('degre_temperature', models.CharField(blank=True, max_length=50)),
                ('localisation', models.CharField(blank=True, max_length=150)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_speciales', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GicleurIdentificationSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('systeme', models.CharField(blank=True, max_length=150)),
                ('zone_protegee', models.CharField(blank=True, max_length=150)),
                ('marque', models.CharField(blank=True, max_length=150)),
                ('modele', models.CharField(blank=True, max_length=150)),
                ('annee', models.CharField(blank=True, max_length=4)),
                ('diametre', models.CharField(blank=True, max_length=50)),
                ('lieu_robinet_essai', models.CharField(blank=True, max_length=150)),
                ('pompe_surpression', models.CharField(blank=True, max_length=150)),
                ('compresseur_air', models.CharField(blank=True, max_length=150)),
                ('plaque_signaletique', models.CharField(blank=True, max_length=150)),
                ('identification_complete', models.CharField(blank=True, max_length=150)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications_systemes', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='GicleurEssaiEcoulement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('pression_systeme', models.CharField(blank=True, help_text='Pression du système, en lbs.', max_length=20)),
                ('localisation_drain', models.CharField(blank=True, max_length=150)),
                ('dimension_tuyau', models.CharField(blank=True, max_length=50)),
                ('pression_statique', models.CharField(blank=True, max_length=20)),
                ('pression_residuelle', models.CharField(blank=True, max_length=20)),
                ('pression_apres', models.CharField(blank=True, max_length=20)),
                ('etat_marche_arret', models.CharField(blank=True, choices=[('marche', 'Marche'), ('arret', 'Arrêt')], max_length=10)),
                ('heure_marche_arret', models.CharField(blank=True, max_length=10)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essais_ecoulement', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GicleurAmelioration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('texte', models.TextField()),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameliorations', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='CertificatGicleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('certificat_envoye', models.BooleanField(default=False, help_text='True quand le superviseur envoie explicitement le certificat au citoyen.')),
                ('mode_envoi', models.CharField(blank=True, choices=[('direct', 'Courriel direct'), ('citoyen', 'Espace citoyen')], max_length=10)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('envoye_a', models.CharField(blank=True, help_text="Courriel ou nom d'utilisateur destinataire, au moment de l'envoi.", max_length=255)),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_gicleurs_emis', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='GicleurReponseChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=2)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('code_item', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=300)),
                ('type_reponse', models.CharField(choices=[('choix', 'Oui / S/O / Non'), ('texte', 'Texte libre')], default='choix', max_length=10)),
                ('reponse', models.CharField(blank=True, choices=[('oui', 'Oui'), ('na', 'S/O'), ('non', 'Non')], max_length=3)),
                ('valeur_texte', models.TextField(blank=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_checklist', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('rapport', 'code_item')},
            },
        ),
        migrations.CreateModel(
            name='GicleurCommentaireSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=2)),
                ('texte', models.TextField()),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_sections', to='inspections.rapportgicleur')),
            ],
            options={
                'ordering': ['rapport', 'section'],
                'unique_together': {('rapport', 'section')},
            },
        ),
    ]
