# Generated by Django 6.0.3 on 2026-09-26 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copier_photos_gicleur(apps, schema_editor):
    # Les photos déjà prises sur des rapports gicleur passent dans la table
    # commune, sans perte.
    Ancienne = apps.get_model("inspections", "PhotoAnomalieGicleur")
    Nouvelle = apps.get_model("inspections", "PhotoAnomalie")
    for p in Ancienne.objects.all():
        copie = Nouvelle.objects.create(
            rapport_gicleur_id=p.rapport_id, image=p.image, emplacement=p.emplacement,
            description=p.description, ajoutee_par_id=p.ajoutee_par_id, ordre=p.ordre,
        )
        # date_ajout est auto_now_add : on remet la date d'origine après coup.
        Nouvelle.objects.filter(pk=copie.pk).update(date_ajout=p.date_ajout)


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0031_rapportgicleur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAnomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('emplacement', models.CharField(help_text='Titre de la photo, ex. « Sous-sol — salle mécanique ».', max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('ajoutee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport_cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.rapportcuisine')),
                ('rapport_eclairage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.rapporteclairageurgence')),
                ('rapport_extincteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.rapportextincteur')),
                ('rapport_gicleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.rapportgicleur')),
                ('rapport_incendie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.rapport')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.RunPython(copier_photos_gicleur, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='PhotoAnomalieGicleur',
        ),
        migrations.AddConstraint(
            model_name='photoanomalie',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rapport_incendie__isnull', False), ('rapport_extincteur__isnull', True), ('rapport_eclairage__isnull', True), ('rapport_cuisine__isnull', True), ('rapport_gicleur__isnull', True)), models.Q(('rapport_incendie__isnull', True), ('rapport_extincteur__isnull', False), ('rapport_eclairage__isnull', True), ('rapport_cuisine__isnull', True), ('rapport_gicleur__isnull', True)), models.Q(('rapport_incendie__isnull', True), ('rapport_extincteur__isnull', True), ('rapport_eclairage__isnull', False), ('rapport_cuisine__isnull', True), ('rapport_gicleur__isnull', True)), models.Q(('rapport_incendie__isnull', True), ('rapport_extincteur__isnull', True), ('rapport_eclairage__isnull', True), ('rapport_cuisine__isnull', False), ('rapport_gicleur__isnull', True)), models.Q(('rapport_incendie__isnull', True), ('rapport_extincteur__isnull', True), ('rapport_eclairage__isnull', True), ('rapport_cuisine__isnull', True), ('rapport_gicleur__isnull', False)), _connector='OR'), name='photo_anomalie_un_seul_rapport'),
        ),
    ]
