# Generated by Django 6.0.3 on 2026-09-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0033_rapportcuisine_schema_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportcuisine',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='envoye_a',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='rapport_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rapporteclairageurgence',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapporteclairageurgence',
            name='envoye_a',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rapporteclairageurgence',
            name='rapport_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
