# Generated by Django 6.0.3 on 2026-10-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0036_jeton_certificats_incendie_gicleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='extincteuritem',
            name='non_conformites',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
