# Generated by Django 6.0.3 on 2026-10-08 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0037_extincteur_non_conformites'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoanomalie',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.sectiondispositif'),
        ),
    ]
