# Generated by Django 6.0.3 on 2026-10-09 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0038_photo_anomalie_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_mime', models.CharField(default='application/octet-stream', max_length=100)),
                ('taille', models.PositiveIntegerField(default=0, help_text="Taille d'origine, en octets.")),
                ('empreinte', models.CharField(db_index=True, max_length=64)),
                ('compresse', models.BooleanField(default=False)),
                ('contenu', models.BinaryField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CycleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(help_text='Année de début — sert au libellé « Cycle 2026 ».')),
                ('date_debut', models.DateField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('note_fermeture', models.CharField(blank=True, max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='inspections.batiment')),
                ('ferme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_fermes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.AddField(
            model_name='rapport',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text="Cycle d'inspection du bâtiment (voir dossier.py).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_incendie', to='inspections.cycleinspection'),
        ),
        migrations.AddField(
            model_name='rapportcuisine',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text="Cycle d'inspection du bâtiment (voir dossier.py).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_cuisine', to='inspections.cycleinspection'),
        ),
        migrations.AddField(
            model_name='rapporteclairageurgence',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text="Cycle d'inspection du bâtiment (voir dossier.py).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_eclairage', to='inspections.cycleinspection'),
        ),
        migrations.AddField(
            model_name='rapportextincteur',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text="Cycle d'inspection du bâtiment (voir dossier.py).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_extincteurs', to='inspections.cycleinspection'),
        ),
        migrations.AddField(
            model_name='rapportgicleur',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text="Cycle d'inspection du bâtiment (voir dossier.py).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_gicleurs', to='inspections.cycleinspection'),
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_envoi', models.CharField(choices=[('documents', 'Rapports et certificats'), ('notification', 'Avis de documents disponibles'), ('renvoi', "Renvoi d'un document"), ('reparations', 'Avis de réparations requises'), ('rappel', "Rappel d'inspection"), ('planification', "Planification d'une visite"), ('manuel', 'Envoi depuis le dossier')], max_length=15)),
                ('mode', models.CharField(choices=[('direct', 'Courriel avec documents joints'), ('plateforme', 'Espace client')], default='direct', max_length=12)),
                ('destinataire', models.CharField(max_length=255)),
                ('destinataire_nom', models.CharField(blank=True, max_length=150)),
                ('sujet', models.CharField(max_length=300)),
                ('corps_html', models.TextField(blank=True)),
                ('message', models.TextField(blank=True, help_text="Message ajouté par l'expéditeur, s'il y a lieu.")),
                ('rapports', models.JSONField(blank=True, default=list, help_text="[{module, id, libelle}] concernés par l'envoi.")),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], default='envoye', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Identifiant du message chez le fournisseur de courriel.', max_length=120)),
                ('erreur', models.CharField(blank=True, max_length=300)),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='inspections.batiment')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois', to='inspections.cycleinspection')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvenementCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='inspections.cycleinspection')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EnvoiPieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(choices=[('document', 'Document généré (rapport, certificat)'), ('ajout', "Fichier ajouté par l'expéditeur (facture…)")], default='document', max_length=10)),
                ('envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='inspections.envoi')),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes', to='inspections.fichierarchive')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('incendie', "Système d'alarme incendie"), ('extincteur', 'Extincteurs portatifs'), ('eclairage', "Éclairage d'urgence"), ('cuisine', 'Système de cuisine'), ('gicleur', 'Gicleurs')], max_length=12)),
                ('rapport_id', models.PositiveIntegerField(help_text='Identifiant du rapport du module (conservé même si le rapport est supprimé).')),
                ('type_document', models.CharField(choices=[('rapport', 'Rapport'), ('certificat', 'Certificat'), ('avis', 'Avis de non-conformité')], default='rapport', max_length=12)),
                ('titre', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, help_text="Numéro du certificat, s'il y a lieu.", max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('remplacee_le', models.DateTimeField(blank=True, help_text="Date à laquelle une version plus récente l'a remplacée.", null=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='inspections.batiment')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='inspections.cycleinspection')),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='inspections.fichierarchive')),
            ],
            options={
                'ordering': ['module', 'type_document', '-version'],
            },
        ),
    ]
