# Generated by Django 6.0.3 on 2026-10-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0040_cycles_rapports_existants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_famille',
            field=models.CharField(blank=True, help_text='Particulier seulement.', max_length=75),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, help_text='Particulier seulement.', max_length=75),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('entreprise', 'Entreprise'), ('particulier', 'Particulier')], default='entreprise', max_length=12),
        ),
    ]
