export type ItemType = 'oui_non_so' | 'texte'

export interface E2Item {
  id: string
  label: string
  type: ItemType
  placeholder?: string
}

export interface E2Section {
  id: string
  titre: string
  hasLocDesc: boolean
  items: E2Item[]
  isTexteLibre?: boolean
}

export const E2_STRUCTURE: E2Section[] = [
  {
    id: 'e2_1',
    titre: 'E2.1 — Essai du poste de contrôle principal',
    hasLocDesc: true,
    items: [
      { id: 'A', label: "Fonctionnement de l'indicateur visuel de mise sous tension", type: 'oui_non_so' },
      { id: 'B', label: 'Fonctionnement du signal de défectuosité visuel commun', type: 'oui_non_so' },
      { id: 'C', label: 'Fonctionnement du signal de défectuosité sonore commun', type: 'oui_non_so' },
      { id: 'D', label: "Fonctionnement de l'interrupteur de signalisation sonore de défectuosité", type: 'oui_non_so' },
      { id: 'E', label: "Fonctionnement du signal de défectuosité de l'alimentation principale", type: 'oui_non_so' },
      { id: 'F', label: 'Fuite à la terre sur signal de défectuosité positif et négatif', type: 'oui_non_so' },
      { id: 'G', label: "Fonctionnement du signal d'alerte", type: 'oui_non_so' },
      { id: 'H', label: "Fonctionnement du signal d'alarme", type: 'oui_non_so' },
      { id: 'I', label: "Fonctionnement du passage automatique de signal d'alerte à signal d'alarme", type: 'oui_non_so' },
      { id: 'J', label: "Fonctionnement du passage manuel de signal d'alerte à signal d'alarme", type: 'oui_non_so' },
      { id: 'K', label: "Caractéristique d'annulation du passage automatique de signal d'alerte à signal d'alarme fonctionnant sur un réseau à deux étapes", type: 'oui_non_so' },
      { id: 'L', label: "Fonctionnement de la désactivation de l'interruption du signal d'alarme sonore", type: 'oui_non_so' },
      { id: 'M', label: "Fonctionnement de l'interruption manuelle du signal d'alarme sonore", type: 'oui_non_so' },
      { id: 'N', label: "Fonctionnement de l'indicateur visuel d'interruption du signal d'alarme sonore", type: 'oui_non_so' },
      { id: 'O', label: "Déclenchement automatique du signal d'alarme sonore, après interruption, en cas de réception d'alarme subséquente", type: 'oui_non_so' },
      { id: 'P', label: "Temporisation automatique d'annulation du signal d'alarme sonore", type: 'oui_non_so' },
      { id: 'Q', label: "Signaux d'alerte et d'alarme sonores et visuels programmés et fonctionnant conformément à la conception et aux spécifications", type: 'oui_non_so' },
      { id: 'R', label: "Fonctionnement d'alarme et de surveillance du circuit d'entrée, y compris les indications sonores et visuelles", type: 'oui_non_so' },
      { id: 'S', label: "La surveillance des défauts sur un circuit d'entrée entraine une indication de défectuosité", type: 'oui_non_so' },
      { id: 'T', label: "Fonctionnement des indicateurs d'alarme du circuit de sortie", type: 'oui_non_so' },
      { id: 'U', label: "La surveillance des défauts sur un circuit de sortie entraine une indication de défectuosité", type: 'oui_non_so' },
      { id: 'V', label: "Essai d'indicateur visuel (essai de lampe)", type: 'oui_non_so' },
      { id: 'W', label: "Séquences de signal codé fonctionnant au moins le nombre de fois nécessaire et suivies d'un déclenchement de signal d'alarme approprié", type: 'oui_non_so' },
      { id: 'X', label: "Séquences de signal codé non interrompues par une alarme subséquente", type: 'oui_non_so' },
      { id: 'Y', label: "Une dérivation du dispositif auxiliaire provoque un signal de défectuosité", type: 'oui_non_so' },
      { id: 'Z', label: "Fonctionnement du circuit d'entrée vers le circuit de sortie, y compris les circuits des dispositifs auxiliaires, pour assurer le bon fonctionnement du programme", type: 'oui_non_so' },
      { id: 'AA', label: "Fonctionnement du réarmement du réseau avertisseur d'incendie", type: 'oui_non_so' },
      { id: 'BB', label: "Fonctionnement de la commutation de l'alimentation principale à l'alimentation de secours", type: 'oui_non_so' },
      { id: 'CC', label: 'Vérification de la confirmation du changement d\'état (détecteurs de fumée seulement ; se reporter au paragraphe 5.4.7.3)', type: 'oui_non_so' },
      { id: 'DD', label: "Réception de la transmission d'un signal d'alarme à la centrale de réception d'alarme incendie", type: 'oui_non_so' },
      { id: 'EE', label: "Réception de la transmission d'un signal de surveillance à la centrale de réception d'alarme incendie", type: 'oui_non_so' },
      { id: 'FF', label: "Réception de la transmission d'un signal de défectuosité à la centrale de réception d'alarme incendie", type: 'oui_non_so' },
      { id: 'GG', label: "Nom et numéro de téléphone de la centrale de réception d'alarme incendie", type: 'oui_non_so' },
      { id: 'HH', label: "Le déclenchement du sectionneur de la centrale de réception d'alarme incendie produit une indication de défectuosité précise au poste de contrôle et achemine un signal de défectuosité à la centrale", type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_2',
    titre: 'E2.2 — Essai du système de recherche de personnes et téléphones d\'urgence',
    hasLocDesc: true,
    items: [
      { id: 'A', label: "Fonctionnement de l'indicateur de mise sous tension", type: 'oui_non_so' },
      { id: 'B', label: 'Fonctionnement du signal de défectuosité visuel commun', type: 'oui_non_so' },
      { id: 'C', label: 'Fonctionnement du signal de défectuosité sonore commun', type: 'oui_non_so' },
      { id: 'D', label: "Fonctionnement de l'interrupteur de signalisation sonore de défectuosité", type: 'oui_non_so' },
      { id: 'E', label: 'Fonctionnement de la recherche phonique générale de personnes, y compris l\'indication visuelle', type: 'oui_non_so' },
      { id: 'F', label: 'Fonctionnement des circuits de sortie en cas de recherche phonique sélective de personnes, y compris l\'indication visuelle', type: 'oui_non_so' },
      { id: 'G', label: 'Fonctionnement des circuits de sortie pour défectuosité de recherche phonique sélective de personnes, y compris l\'indication visuelle', type: 'oui_non_so' },
      { id: 'H', label: 'Fonctionnement du microphone, y compris bouton de communication', type: 'oui_non_so' },
      { id: 'I', label: "Fonctionnement de la recherche de personnes ne nuisant pas à la temporisation initiale de désactivation de la signalisation sonore d'alerte et d'alarme", type: 'oui_non_so' },
      { id: 'J', label: 'Fonctionnement de la recherche générale de personnes', type: 'oui_non_so' },
      { id: 'K', label: "Passage automatique à un amplificateur de relève en cas de panne d'un amplificateur normal", type: 'oui_non_so' },
      { id: 'L', label: "Circuits de réception d'appel d'un téléphone d'urgence, y compris les indications sonores et visuelles", type: 'oui_non_so' },
      { id: 'M', label: "Fonctionnement des circuits des téléphones d'urgence, y compris les communications phoniques bidirectionnelles", type: 'oui_non_so' },
      { id: 'N', label: "Fonctionnement des circuits de signalisation de défectuosité des téléphones d'urgence, y compris l'indication visuelle", type: 'oui_non_so' },
      { id: 'O', label: "Fonctionnement des communications verbales par téléphone d'urgence", type: 'oui_non_so' },
      { id: 'P', label: "Fonctionnement de la tonalité d'utilisation ou de disponibilité des téléphones d'urgence, au combiné", type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_3',
    titre: 'E2.3 — Vérification du poste de contrôle',
    hasLocDesc: true,
    items: [
      { id: 'A', label: 'Désignations du circuit d\'entrée correctement indiquées et correspondant aux dispositifs raccordés', type: 'oui_non_so' },
      { id: 'B', label: 'Désignations du circuit de sortie correctement repérées et correspondant à celles des dispositifs raccordés', type: 'oui_non_so' },
      { id: 'C', label: 'Désignations des fonctions de contrôle communes et des indicateurs communs correctes', type: 'oui_non_so' },
      { id: 'D', label: 'Composants enfichables et modules solidement en place', type: 'oui_non_so' },
      { id: 'E', label: 'Câbles enfichables solidement en place', type: 'oui_non_so' },
      { id: 'F', label: 'Date, version et révision des microprogrammes et des programmes logiciels consignés', type: 'texte', placeholder: 'ex. 2024-01-15 v2.3' },
      { id: 'G', label: 'Propre et exempt de poussière et de saleté', type: 'oui_non_so' },
      { id: 'H', label: 'Fusibles conformes aux spécifications des fabricants', type: 'oui_non_so' },
      { id: 'I', label: 'Verrouillage du poste de contrôle ou du répondeur', type: 'oui_non_so' },
      { id: 'J', label: 'Solidité des connexions du câblage aux dispositifs', type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_4',
    titre: 'E2.4 — Alimentation principale (source d\'alimentation C.A.)',
    hasLocDesc: true,
    items: [
      { id: 'A', label: 'Protection fusible correspondant aux caractéristiques nominales affichées par le fabricant', type: 'oui_non_so' },
      { id: 'B', label: 'Alimentation suffisante pour les besoins du réseau', type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_5',
    titre: 'E2.5 — Alimentation de secours (batterie)',
    hasLocDesc: true,
    items: [
      { id: 'A', label: 'Type de batterie recommandée par le fabricant', type: 'oui_non_so' },
      { id: 'B', label: 'Caractéristiques nominales suffisantes après des calculs fondés sur la pleine charge du réseau', type: 'oui_non_so' },
      { id: 'C', label: 'Tension de batterie lorsque la source d\'alimentation principale est sous tension', type: 'texte', placeholder: 'ex. 26.54V' },
      { id: 'D', label: 'Tension et courant de batterie, alimentation principale coupée, mode surveillance', type: 'texte', placeholder: 'ex. 26.3V / 0.19A' },
      { id: 'E', label: 'Tension et courant de batterie, alimentation principale coupée, pleine charge', type: 'texte', placeholder: 'ex. 25.85V / 0.88A' },
      { id: 'F', label: 'Courant de charge', type: 'texte', placeholder: 'ex. 0.51A' },
      { id: 'G', label: 'Absence de dommages matériels', type: 'oui_non_so' },
      { id: 'H', label: 'Bornes nettoyées et lubrifiées', type: 'oui_non_so' },
      { id: 'I', label: 'Bornes serrées', type: 'oui_non_so' },
      { id: 'J', label: "Niveau d'électrolyte correct", type: 'oui_non_so' },
      { id: 'K', label: "Densité de l'électrolyte conforme aux spécifications du fabricant", type: 'oui_non_so' },
      { id: 'L', label: "Aucune fuite d'électrolyte", type: 'oui_non_so' },
      { id: 'M', label: 'Ventilation adéquate', type: 'oui_non_so' },
      { id: 'N', label: 'Code dateur du fabricant ou date de mise en service', type: 'texte', placeholder: 'ex. 2023' },
      { id: 'O', label: 'Débranchement provoque signal de défectuosité', type: 'oui_non_so' },
      { id: 'Q', label: 'Capacité de la batterie calculée', type: 'texte', placeholder: 'ex. 5Ah' },
      { id: 'R', label: "Après la fin des essais, tension aux bornes de la batterie", type: 'texte', placeholder: 'ex. 26.03V' },
      { id: 'S', label: "Après les essais, la tension de la batterie n'est pas inférieure à 85% de la tension nominale", type: 'oui_non_so' },
      { id: 'T', label: "Le générateur fournit l'alimentation au circuit C.A. qui dessert le réseau avertisseur d'incendie", type: 'oui_non_so' },
      { id: 'U', label: "Une situation de défectuosité au générateur d'urgence provoque un signal de défectuosité sonore commun ainsi qu'une indication visuelle", type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_6',
    titre: 'E2.6 — Répondeur ou panneau d\'annonce — type I',
    hasLocDesc: true,
    items: [
      { id: 'A', label: "Fonctionnement de l'indicateur de mise sous tension", type: 'oui_non_so' },
      { id: 'B', label: "Zones d'entrée individuelles d'alarme et de surveillance indiquées clairement, de manière distincte", type: 'oui_non_so' },
      { id: 'C', label: "Étiquettes de désignation des zones individuelles d'alarme et de surveillance correctement marquées", type: 'oui_non_so' },
      { id: 'D', label: 'Fonctionnement du signal de défectuosité commun', type: 'oui_non_so' },
      { id: 'E', label: "Fonctionnement de l'essai d'indicateur visuel (essai de lampe)", type: 'oui_non_so' },
      { id: 'F', label: 'Surveillance du câblage d\'entrée du poste de contrôle ou du répondeur', type: 'oui_non_so' },
      { id: 'G', label: "Fonctionnement de l'indicateur visuel d'interruption du signal d'alarme sonore", type: 'oui_non_so' },
      { id: 'H', label: 'Contacts des fonctions auxiliaires fonctionnant conformément à la conception et aux spécifications', type: 'oui_non_so' },
      { id: 'I', label: 'Fonctionnement des autres indicateurs visuels des fonctions auxiliaires', type: 'oui_non_so' },
      { id: 'J', label: "Actionnement manuel du signal d'alarme et indication", type: 'oui_non_so' },
      { id: 'K', label: "Affichages visibles dans le lieu de l'installation", type: 'oui_non_so' },
      { id: 'L', label: "Fonctionnement sur l'alimentation de secours", type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_7',
    titre: 'E2.7 — Répondeur ou panneau d\'annonce — type II',
    hasLocDesc: true,
    items: [
      { id: 'A', label: "Fonctionnement de l'indicateur de mise sous tension", type: 'oui_non_so' },
      { id: 'B', label: "Fonctionnement de l'indication de zone individuelle d'alarme et de surveillance", type: 'oui_non_so' },
      { id: 'C', label: "Étiquettes de désignation des zones individuelles d'alarme et de surveillance correctement marquées", type: 'oui_non_so' },
      { id: 'D', label: 'Fonctionnement du signal de défectuosité commun', type: 'oui_non_so' },
      { id: 'E', label: "Fonctionnement de l'essai d'indicateur visuel (essai de lampe)", type: 'oui_non_so' },
      { id: 'F', label: 'Surveillance du câblage d\'entrée du poste de contrôle ou du répondeur', type: 'oui_non_so' },
      { id: 'G', label: "Fonctionnement de l'indicateur visuel d'interruption du signal d'alarme sonore", type: 'oui_non_so' },
      { id: 'H', label: 'Contacts des fonctions auxiliaires fonctionnant conformément à la conception et aux spécifications', type: 'oui_non_so' },
      { id: 'I', label: 'Fonctionnement des autres indicateurs visuels des fonctions auxiliaires', type: 'oui_non_so' },
      { id: 'J', label: "Actionnement manuel du signal d'alarme et indication", type: 'oui_non_so' },
      { id: 'K', label: "Affichages visibles dans le lieu de l'installation", type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_8',
    titre: 'E2.8 — Indicateur d\'alarme à distance',
    hasLocDesc: true,
    items: [
      { id: 'A', label: 'Surveillance du câblage d\'entrée du poste de contrôle ou du répondeur', type: 'oui_non_so' },
      { id: 'B', label: 'Fonctionnement du signal visuel de défectuosité', type: 'oui_non_so' },
      { id: 'C', label: 'Fonctionnement du signal sonore de défectuosité', type: 'oui_non_so' },
      { id: 'D', label: "Fonctionnement de l'interruption du signal sonore de défectuosité", type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_9',
    titre: 'E2.9 — Imprimante',
    hasLocDesc: true,
    items: [
      { id: 'A', label: 'Fonctionnement de l\'imprimante selon la conception et les spécifications', type: 'oui_non_so' },
      { id: 'B', label: "Impression correcte de la zone de chaque dispositif de déclenchement d'alarme", type: 'oui_non_so' },
      { id: 'C', label: 'Alimentation à la tension nominale', type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_10',
    titre: 'E2.10 — Liaisons de données',
    hasLocDesc: true,
    items: [
      { id: 'A', label: "Confirmer la réception d'un signal de défectuosité par le poste de contrôle en cas de boucle ouverte pour chaque liaison de données", type: 'oui_non_so' },
      { id: 'B', label: "Si des modules d'isolation en cas de défaut font partie de liaisons de données, court-circuiter le câblage et confirmer l'annonce de la défectuosité", type: 'oui_non_so' },
      { id: 'C_i', label: 'Poste de contrôle et poste de contrôle', type: 'oui_non_so' },
      { id: 'C_ii', label: 'Poste de contrôle et répondeur', type: 'oui_non_so' },
      { id: 'C_iii', label: 'Répondeur et répondeur', type: 'oui_non_so' },
    ],
  },
  {
    id: 'e2_11',
    titre: 'E2.11 — Dispositifs auxiliaires',
    hasLocDesc: false,
    isTexteLibre: true,
    items: [
      { id: 'remarques', label: 'Remarques', type: 'texte', placeholder: 'Aucun dispositif auxiliaire mis à l\'essai' },
    ],
  },
  {
    id: 'e2_12',
    titre: 'E2.12 — Remarques générales',
    hasLocDesc: false,
    isTexteLibre: true,
    items: [
      { id: 'remarques', label: 'Remarques', type: 'texte', placeholder: 'Remarques supplémentaires...' },
    ],
  },
]
