# Generated by Django 6.0.3 on 2026-08-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text="Vide pour un super admin — n'appartient à aucune organisation.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('superviseur', 'Superviseur'), ('technicien', 'Technicien'), ('citoyen', 'Citoyen')], default='citoyen', max_length=20),
        ),
    ]
