# Generated by Django 6.0.3 on 2026-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_organisation_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('superviseur', 'Superviseur'), ('technicien', 'Technicien'), ('citoyen', 'Contact client')], default='citoyen', max_length=20),
        ),
    ]
